# Generated by Django 5.2.8 on 2025-12-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_basico', models.CharField(max_length=8)),
                ('cnpj_ordem', models.CharField(max_length=4)),
                ('cnpj_dv', models.CharField(max_length=2)),
                ('identificador_matriz_filial', models.CharField(max_length=1)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('situacao_cadastral', models.CharField(max_length=30)),
                ('data_situacao_cadastral', models.CharField(blank=True, max_length=10)),
                ('motivo_situacao_cadastral', models.CharField(blank=True, max_length=10)),
                ('nome_cidade_exterior', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('data_inicio_atividade', models.CharField(blank=True, max_length=10)),
                ('cnae_fiscal_principal', models.CharField(max_length=10)),
                ('cnae_fiscal_secundaria', models.TextField(blank=True)),
                ('tipo_logradouro', models.CharField(blank=True, max_length=20)),
                ('logradouro', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=200)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=100)),
                ('ddd1', models.CharField(blank=True, max_length=4)),
                ('telefone1', models.CharField(blank=True, max_length=10)),
                ('ddd2', models.CharField(blank=True, max_length=4)),
                ('telefone2', models.CharField(blank=True, max_length=10)),
                ('ddd_fax', models.CharField(blank=True, max_length=4)),
                ('fax', models.CharField(blank=True, max_length=10)),
                ('correio_eletronico', models.CharField(blank=True, max_length=100)),
                ('situacao_especial', models.CharField(blank=True, max_length=100)),
                ('data_situacao_especial', models.CharField(blank=True, max_length=10)),
                ('razao_social', models.CharField(max_length=200)),
                ('natureza_juridica', models.CharField(max_length=100)),
                ('qualificacao_responsavel', models.CharField(max_length=100)),
                ('capital_social', models.DecimalField(decimal_places=2, max_digits=15)),
                ('porte_empresa', models.CharField(max_length=50)),
                ('ente_federativo_responsavel', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
