# Generated by Django 5.2.8 on 2025-12-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='natureza_juridica',
            field=models.CharField(max_length=255),
        ),
    ]
