# Generated by Django 5.2.8 on 2025-12-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_natureza_juridica'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
